# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbb176f3fcf4444afdd041544607d50b1da4e10221551bc01a40d3b0bb52472b15c046c0f5a0316bc0f3b91ef19df978438bf0ae338bb83ed799d4b2a262a38

test:
  secret_key_base: 534471c1cc0b017b2e9ea84c444676bf7824d4e82706510a90852855afa7930511db83398ecb3cca55717fa2c49177ca182bf66442872045b66d307c6f5cc7dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
